### ISSUE TITLE
Version not working when startup of server

### ISSUE THREAD

**Issue by TobiTibb** [eirikh1996/Movecraft#20] opened 2019-11-12 08:15 UTC
**Describe the bug**
The version doesn't work on startup of server on Paper 1.14.4

**To Reproduce**
1. When running run.bat

**Expected behavior**
Movecraft not working on paper

**Screenshots**
![Bugged](https://user-images.githubusercontent.com/57655932/68653687-1f322c00-0591-11ea-99dd-53157b02d559.png)

**Versions (please complete the following information):**
 - Movecraft 7.0 for 1.10 - 1.14.4 Beta 2
 - Java [e.g. JDK 8.0.1]
 - Minecraft 1.14.4

**Comment by eirikh1996** [comment] 2019-11-15 15:05
That is a Movecraft-Factions, not a Movecraft stacktrace

**Comment by TobiTibb** [comment] 2019-11-15 19:01
![Screenshot_1](https://user-images.githubusercontent.com/57655932/68968327-284c2300-0847-11ea-93c5-c1774d3c0be2.png)

I removed factions and still got an error
my bad

**Comment by eirikh1996** [comment] 2019-11-16 01:18
Seems like an issue with the config.

**Comment by eirikh1996** [comment] 2019-11-16 01:20
btw, this is a duplicate of #18, which was resolved in 7dc74d99250be912ebabe0bfd1505cce3c382720

**Closed by eirikh1996** 2019-11-16 01:20 UTC
Labels: bug
