### ISSUE TITLE
crafts not moving

### ISSUE THREAD

**Issue by nitro77live** [eirikh1996/Movecraft#19] opened 2019-11-09 00:50 UTC
movecraft crafts are not moving via stick or cruise sign

pilot your craft then attempt to use your pilot tool which should result in no movement of the craft but the teleportation of the player by 1 block, but only for the first click.

the craft does not move the ship but moves teleports the player the where the craft should've ended up, but only for the first right click of the pilot tool then all movement stops

 - Movecraft: v7.0.0_beta_1
 - Java 8 openj9
 - Minecraft 1.14.4

logs
[WARNING] .... [Movecraft] Task #81 for Movecraft v7.0.0_beta_1 generated an exception

java.lang.NoClassDefFoundError: javafx/util/Pair

at net.countercraft.movecraft.compat.v1_14_R1.NextTickProvider.registerWorld(NextTickProvider.java:33) ~[?:?]

at net.countercraft.movecraft.compat.v1_14_R1.NextTickProvider.getNextTick(NextTickProvider.java:39) ~[?:?]

at net.countercraft.movecraft.compat.v1_14_R1.IWorldHandler.translateCraft(IWorldHandler.java:180) ~[?:?]

at net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:165) ~[?:?]

at net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:58) ~[?:?]

at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]

at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-175]

at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-175]

at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]

at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by eirikh1996** [comment] 2019-11-16 01:23
Duplicate of #18

**Closed by eirikh1996** 2019-11-16 01:23 UTC
Labels: bug

**Comment by eirikh1996** [comment] 2019-11-16 01:30
Resolved in 2f48d104d2c020eecc4f0fdfa029adbb88737170
