### ISSUE TITLE
Riding entities won't work on crafts

### ISSUE THREAD

**Issue by Jokkaj** [eirikh1996/Movecraft#37] opened 2020-04-17 16:43 UTC
When a player rides an entity such as a horse or a minecart both the player and the entity won't move with the craft even if the craft has the "onlyMovePlayers" tag set to false in his .craft file and can move individual entities just fine.
An entity riding another entity such as a cow in a boat or a spider jockey (skeleton riding a spider) will just separate when you move the craft, this is very annoyng when you are trying to move rare mobs such as polar bears, shulkers or elder guardians using boats and this breaks every custom forniture plugin/datapacks (they use rideable invisibile horses/armorstands/arrows and fixing this bug should make them fully compatibile with movecraft).

I am using the latest release on paper 1.15.2 with the latest release of worldedit 
you can use /summon minecraft:spider ~ ~1 ~ {Passengers:[{id:"minecraft:skeleton"}]} to summon a spider jockey for testing purposes.

**Comment by eirikh1996** [comment] 2020-04-20 10:27
Duplicate of #35

**Closed by eirikh1996** 2020-04-20 10:27 UTC
Labels: bug
